---
version: "3"

services:

  demo:
    build:
      context: ./
      dockerfile: Dockerfile
    image: demo:1.0
    container_name: demo
    ports:
      - 8081:8080
    # volumes:
      # - ./:/work
    restart: always
